### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by adamlewkowicz** [alk831/ediary-react-native#8]
### Critical:
- [x] - Improve UX of user create sliders
- [x] - Display error when async operation failed (eg. infinite product search)
- [x] - Add error reporting system
- [x] - Remove second day text from date picker comp

### Improvements:
- [ ] #116
- [x] - refactor numeric input with value limit
- [x] - do not use default portion of 100g if any custom portion is available when adding new product to meal (could use product's portion getter value)
- [x] - add product (and each entity) validation - current solution doesn't trigger `class-validator's` checkers (https://github.com/typeorm/typeorm/issues/2577)
- [x] - refactor product macro properties as embedded property
- [x] - create generic extendable entity that runs `validate` method on update and save by default
- [x] - _throttle product item press on `ProductFinder` screen_ -> allow product item press only once
- [x] - display loading when product is being added to meal, or meal is being created
### Bugs:
- [x] - fix database connection issue ("default" connection already exits in this session / is already 
created)
- [ ] - numeric keyboard doesn't show `dot` button on HTC phone
### Features:
- [x] - refetch data when user is on product finder page and enables connection
- [x] - display text and link to product create page (with barcode in param) when no products for barcode were found
- [ ] - display fixed macro row when scrolling down on homepage
- [x] - use ProductFind input's text (as param) when navigating to ProductCreate as name value
